version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    # environment:
      # QDRANT__SERVICE__API_KEY: "secret_api_key"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:


